### PR TITLE
Merged fix for async functions and infographic

### PR DESCRIPTION
**Pull request by tbtommyb**
I've tested this and it all seems to be working ok. The only think is that closing the visualisation takes a while because it starts a whole new request again rather than just closing the overlay so I'll look at that now.

### CODE REVIEW

**Comment by tbtommyb** [comment]
though the news api seems to be currently down.

**Comment by njsfield** [comment]
Ah just seen you've made a working pull too! I tried to pull in your changes to mine and add some extra callback functionality but if you're sorting the visualisation issues I'll close my pull request now.

**Comment by marisid** [comment]
Hey, good job there! I just tried to checkout your branch to see how it looks like, using the hack from the terminal to make the TextRazor requests but couldn't do it. Can't wait to see it tomorrow! Also, I added a small edit in the css to fix a bug on desktop view (see pull request #24).

**Comment by lucymonie** [comment]
Hey guys, I can't get my Chrome to turn off the security settings so I can't check these and merge them either. I have done some code for the google pie chart in case you want to check it out as an option: the code is [here](https://github.com/lucymonie/api-lucy) and the viz is [here](https://lucymonie.github.io/api-lucy/).

**Comment by lucymonie** [comment]
Marina, I merged yours - I figured it was small enough that it was probably okay to do it!

**Comment by marisid** [comment]
Thanks @lucymonie! Yeah, I couldn't turn off security settings for Chrome either. I really like your pie chart!! If we have time tomorrow, we can add as a second infographic.

**Pull request merged**
